APP_NAME = "局域网课堂互动"
DEFAULT_CLASSROOM_NAME = "默认课堂"
DEFAULT_TCP_PORT = 8765
DISCOVERY_PORT = 38765
DISCOVERY_MAGIC = "classroom_hand_raise_discovery"
PROTOCOL_VERSION = 1

HEARTBEAT_INTERVAL_SECONDS = 5
RECONNECT_INTERVAL_SECONDS = 3
DISCOVERY_BROADCAST_INTERVAL_SECONDS = 2

MAX_FRAME_BYTES = 8 * 1024 * 1024
MAX_SCREENSHOT_BYTES = 2 * 1024 * 1024
MAX_SCREENSHOT_EDGE = 1600

RAISE_HAND_COOLDOWN_SECONDS = 10
FEEDBACK_COOLDOWN_SECONDS = 5
HELP_REQUEST_COOLDOWN_SECONDS = 30

FEEDBACK_OPTIONS = ("可以继续", "我没听懂", "讲慢一点", "请再讲一遍")
